### ISSUE TITLE
CSS layout problem

### ISSUE THREAD

**Issue by zuozhehao** [RMerl/asuswrt-merlin#1192] opened 2017-01-12 14:47 UTC
<img width="1093" alt="qq20170112-224843 2x" src="https://cloud.githubusercontent.com/assets/4464252/21894204/4a82c9f2-d919-11e6-8338-6025d5d34259.png">

On Mac Chrome.

**Comment by petertfm** [comment] 2017-01-12 19:46
Im also getting this on a rt-ac88u but with Chrome Canary (unstable) on Android

**Comment by Cpuroast** [comment] 2017-01-14 06:17
Yeah, getting the same thing on latest Chrome beta, doesn't happen with Safari or Firefox.
Most pages, the tab bar and the frame are separated by a large empty space

DIdn't happen before, so it could be a Chrome regression or a 364.80_2 regression.

**Comment by RMerl** [comment] 2017-01-14 18:25
Kinda pointless looking at this until Chrome gets out of beta.  You might want to check with their developers first, since the current CSS code is working fine with the latest non-beta browser - it means something they changed is causing this.

**Comment by Cpuroast** [comment] 2017-01-14 18:26
Yeah, that's what I figured :)

**Comment by RMerl** [comment] 2017-01-19 22:26
Closing this.  Based on the screenshot, this wasn't tested on Asuswrt-Merlin but on some other firmware.

**Closed by RMerl** 2017-01-19 22:26 UTC

**Comment by Cpuroast** [comment] 2017-01-19 23:02
How is it not Asuswrt-Merlin, it's simply in Chinese. Identical layout as my rt-ac3100 running 364.80_2.

**Comment by RMerl** [comment] 2017-01-20 02:17
They why is the firmware version hidden?  The top showing router model and the Asuswrt-Merlin logo are also truncated, as if the OP wanted to hide something.  My guess is he's running a fork.

**Comment by Cpuroast** [comment] 2017-01-20 12:49
That's entirely possible, it just so happens to have the exact same layout issues as 364.80_2 while using the current beta version of Chrome.

But at this point, since Firefox and Safari have no such issues, I blame Chrome, I'll just see if they eventually fix it before it reaches the final version. If they do not, I suspect more tickets for the same issue will open.
