### ISSUE TITLE
Bug on Firmware:380.65_4Virtual Server / Port Forwarding

### ISSUE THREAD

**Issue by Piradoxlanieve** [RMerl/asuswrt-merlin#1305] opened 2017-03-30 21:47 UTC
When I add a new port and click on the apply button it looks like these records are not good at all, I think it's a bug
[http://subefotos.com/ver/?9d91bb409f369966b4644b8207440c61o.jpg](url)
Sorry my bad english

**Comment by RMerl** [comment] 2017-05-10 21:27
Can't reproduce it here.  Looks like your list is corrupted.  Try clearing it first:

```
nvram unset vts_rulelist
nvram commit
```

Asus also changed the way that page worked in 3.0.0.4.380_7378, the new code will be merged into 380.66, which might help avoiding corrupting this entry.

**Closed by RMerl** 2017-05-10 21:27 UTC
